name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: test
      run: |
          pwd
          ls -la

    - name: Build the Docker image
      run: docker build . -f Dockerfile -t public.ecr.aws/j9k0i2s2/dev-or-employee-system:github-actions-image

    - name: Trivy Install
      run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
    
    - name: TrivySacnning
      run: trivy image public.ecr.aws/j9k0i2s2/dev-or-employee-system:github-actions-image
      #trivy image --exit-code 1 --severity HIGH,CRITICAL public.ecr.aws/j9k0i2s2/dev-or-employee-system:github-actions-image

    - name: AWS ECR Login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-west-2"
      run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j9k0i2s2
    
    - name: Push docker image
      run: |
          docker push public.ecr.aws/j9k0i2s2/dev-or-employee-system:github-actions-image